import type { CharacterType } from "../character";

import { Character } from "../character";

const albedo: CharacterType = {
  id: "albedo",
  accentColor: "#f5f1e9",

  name: "Albedo",
  description:
    "A genius known as the Kreideprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius.",
  birthday: [13, 9],

  rarity: 5,
  vision: "GEO",
  weapon: "SWORD",

  constellations: [
    {
      level: 1,
      title: "Flower of Eden",
      description:
        "Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.",
    },
    {
      level: 2,
      title: "Opening of Phanerozoic",
      description:
        "Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s:\n·Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.\n·This effect stacks up to 4 times.",
    },
    {
      level: 3,
      title: "Grace of Helios",
      description:
        "Increases the Level of Abiogenesis: Solar Isotoma by 3.\nMaximum upgrade level is 15.",
    },
    {
      level: 4,
      title: "Descent of Divinity",
      description:
        "Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.",
    },
    {
      level: 5,
      title: "Tide of Hadean",
      description:
        "Increases the Level of Rite of Progeniture: Tectonic Tide by 3.\nMaximum upgrade level is 15.",
    },
    {
      level: 6,
      title: "Dust of Purification",
      description:
        "Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.",
    },
  ],

  story: [],
};

export default Character.parse(albedo);
